---
# Common plays suitable for all Red Hat-based nodes

- name: Enable EPEL
  yum: name=epel-release state=present

- name: Install Vim
  yum: name=vim-enhanced state=present

- name: Install screen
  yum: name=screen state=present

- name: Update yum cache
  yum: update_cache=yes

- name: Apply initial package set updates
  yum: name=* state=latest
